# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v20.1.3" # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
